FROM ghcr.io/andriykalashnykov/quadmath-cross:v0.0.1-builder AS builder

FROM alpine:3.23.2@sha256:c93cec902b6a0c6ef3b5ab7c65ea36beada05ec1205664a4131d9e8ea13e405d AS runtime

WORKDIR /app

COPY --from=builder /app/hello-x86_64 .
COPY --from=builder /app/hello-arm64 .
COPY --from=builder /app/qm-x86_64 .
#COPY --from=builder /app/float128-x86_64 .
#COPY --from=builder /app/qm-arm64 .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]