FROM ghcr.io/andriykalashnykov/quadmath-cross:v0.0.1-builder AS builder

FROM alpine:3.23.3@sha256:25109184c71bdad752c8312a8623239686a9a2071e8825f20acb8f2198c3f659 AS runtime

WORKDIR /app

COPY --from=builder /app/hello-x86_64 .
COPY --from=builder /app/hello-arm64 .
COPY --from=builder /app/qm-x86_64 .
#COPY --from=builder /app/float128-x86_64 .
#COPY --from=builder /app/qm-arm64 .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]