FROM docker.io/anriykalashnykov/amd64:latest AS builder

FROM arm64v8/alpine:3.20.3 AS runtime

WORKDIR /app

COPY --from=builder /app/hello .
COPY --from=builder /app/qm .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]