ARG BUILDER_IMAGE=docker.io/andriykalashnykov/quadmath-cross:v0.0.2-builder
FROM ${BUILDER_IMAGE} AS builder

FROM alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11 AS runtime

WORKDIR /app

COPY --from=builder /app/hello-x86_64 .
COPY --from=builder /app/hello-arm64 .
COPY --from=builder /app/qm-x86_64 .
COPY --from=builder /app/float128-x86_64 .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]