FROM docker.io/anriykalashnykov/quadmath-cross:v0.0.1-builder AS builder

FROM alpine:3.23.2@sha256:865b95f46d98cf867a156fe4a135ad3fe50d2056aa3f25ed31662dff6da4eb62 AS runtime

WORKDIR /app

COPY --from=builder /app/hello-x86_64 .
COPY --from=builder /app/hello-arm64 .
COPY --from=builder /app/qm-x86_64 .
#COPY --from=builder /app/float128-x86_64 .
#COPY --from=builder /app/qm-arm64 .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]