#FROM docker.io/anriykalashnykov/quadmath-cross:latest-builder AS builder
FROM ghcr.io/anriykalashnykov/quadmath-cross:latest-builder AS builder

FROM alpine:3.20.3 AS runtime

WORKDIR /app

COPY --from=builder /app/hello .
COPY --from=builder /app/qm .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]