FROM ghcr.io/andriykalashnykov/quadmath-cross:v0.0.1-builder AS builder

FROM alpine:3.20.3 AS runtime

WORKDIR /app

COPY --from=builder /app/hello-x86_64 .
COPY --from=builder /app/qm-x86_64 .

# Keep the container running
CMD ["tail", "-f", "/dev/null"]