name: ci

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  docker-image-test:

    runs-on: ubuntu-latest
    name: docker-image-test

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

      - name: GitHub Tag Name
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          make ba

  docker-image-builder:

    if: github.ref_type == 'tag'

    runs-on: ubuntu-latest
    name: docker-image-builder
    needs: [ docker-image-test ]

    steps:

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

      - name: Convert owner to lower case
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Login to image repository
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: GitHub Tag Name
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Docker builder meta
        id: meta_builder
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: ghcr.io/${{ env.OWNER_LC }}/quadmath-cross
          flavor: |
            latest=false
            suffix=-builder
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern=v{{version}}
          labels: |
            org.opencontainers.image.vendor=Andriy Kalashnykov - andriykalashnykov@gmail.com
            org.opencontainers.image.title=Cross compile quadmath - amd64 builder
            org.opencontainers.image.description=Cross compile quadmath - amd64 builder
            org.opencontainers.image.licenses=MIT
            org.opencontainers.image.version=${{  github.ref_name }}"
            io.artifacthub.package.readme-url=https://raw.githubusercontent.com/AndriyKalashnykov/quadmath-cross/main/README.md
            io.artifacthub.package.maintainers=[{\"name\":\"Andriy Kalashnykov\",\"email\":\"andriykalashnykov@gmail.com\"}]
            io.artifacthub.package.license=MIT

      - name: Build and push docker_builder
        id: docker_builder
        uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6
        with:
          context: .
          file: ./Dockerfile.builder
          platforms: linux/amd64
          push: ${{ github.ref_type == 'tag' }}
          provenance: false
          tags: ${{ steps.meta_builder.outputs.tags }}
          labels: ${{ steps.meta_builder.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Output docker_builder image digest
        run: echo ${{ steps.docker_builder.outputs.digest }}

  docker-image-runtime:

      if: github.ref_type == 'tag'

      runs-on: ubuntu-latest
      name: docker-image-runtime
      needs: [ docker-image-test, docker-image-builder ]

      steps:

        - name: Checkout code
          uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
          with:
            fetch-depth: 0

        - name: Set up QEMU
          uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3

        - name: Convert owner to lower case
          run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          env:
            OWNER: '${{ github.repository_owner }}'

        - name: Login to image repository
          uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GH_ACCESS_TOKEN }}

        - name: GitHub Tag Name
          run: |
            echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
            echo "Tag name from github.ref_name: ${{  github.ref_name }}"

        - name: Docker runtime meta
          id: meta_runtime
          uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
          with:
            images: ghcr.io/${{ env.OWNER_LC }}/quadmath-cross
            flavor: |
              latest=false
              suffix=-runtime
            tags: |
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr
              type=semver,pattern=v{{version}}
            labels: |
              org.opencontainers.image.vendor=Andriy Kalashnykov - andriykalashnykov@gmail.com
              org.opencontainers.image.title=Cross compile quadmath - runtime
              org.opencontainers.image.description=Cross compile quadmath - runtime
              org.opencontainers.image.licenses=MIT
              org.opencontainers.image.version=${{  github.ref_name }}"
              io.artifacthub.package.readme-url=https://raw.githubusercontent.com/AndriyKalashnykov/quadmath-cross/main/README.md
              io.artifacthub.package.maintainers=[{\"name\":\"Andriy Kalashnykov\",\"email\":\"andriykalashnykov@gmail.com\"}]
              io.artifacthub.package.license=MIT

        - name: Build and push runtime
          id: docker_runtime
          uses: docker/build-push-action@ca877d9245402d1537745e0e356eab47c3520991 # v6
          with:
            context: .
            file: ./Dockerfile.runtme
            platforms: linux/arm64,linux/amd64
            push: ${{ github.ref_type == 'tag' }}
            provenance: false
            tags: ${{ steps.meta_runtime.outputs.tags }}
            labels: ${{ steps.meta_runtime.outputs.labels }}
            cache-from: type=gha
            cache-to: type=gha,mode=max

        - name: Output docker_builder image digest
          run: echo ${{ steps.docker_runtime.outputs.digest }}